name: Purge jsDelivr (button)

# This workflow is triggered manually.
# Go to the "Actions" tab in GitHub → select this workflow on the left →
# click the dropdown "Run workflow" button to run it.
on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/treechart.js
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/treepopup.js
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/familytreedata.js
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/panzoom.js
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/main.js
            https://cdn.jsdelivr.net/gh/ReuvenT/family_history@main/index.css
